import type { Metadata } from "next";
import "./globals.css";

// ایمپورت کامپوننت‌های اختصاصی
import CustomCursor from '@/components/cursor/CustomCursor';
import Navigation from '@/components/navigation/Navigation'; // اضافه شدن ایمپورت منو

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/* کامپوننت‌های سراسری (Global Components) */}
        <CustomCursor />

        {/* اضافه کردن نوار ناوبری (منو) */}
        <Navigation />

        {/* محتوای اصلی صفحات */}
        <main className="flex-1 flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
