import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

// Self-hosted at build time; the size-adjusted fallback (adjustFontFallback, on by default)
// keeps the swap shift-free. Variable names stay distinct from the --font-body / --font-mono
// tokens in globals.css, which reference them. Inter ships its italic too: the hero tagline
// sets body text in italic above the fold.
const inter = Inter({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-inter",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jetbrains-mono",
});

// ایمپورت کامپوننت‌های اختصاصی
import CustomCursor from '@/components/cursor/CustomCursor';
import Navigation from '@/components/navigation/Navigation'; // اضافه شدن ایمپورت منو
import Footer from '@/components/footer/Footer'; // اضافه شدن ایمپورت منو

import LenisProvider from '@/components/providers/LenisProvider'; // مسیر را بر اساس ساختار پروژه خود تنظیم کنید

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <CustomCursor />

        <Navigation />
        <main className="flex-1 flex flex-col">
          <LenisProvider>
            {children}
          </LenisProvider>
        </main>
        <Footer/>
      </body>

    </html>
  );
}
