import type { Metadata } from "next";
import "./globals.css";

// ایمپورت کامپوننت‌های اختصاصی با مسیرهای اصلاح شده
import CustomCursor from '@/components/cursor/CustomCursor';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" // اگر پروژه فارسی است می‌توانید این را به "fa" تغییر دهید
      className="h-full antialiased"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/* اضافه کردن افکت‌ها و ماوس سفارشی در بالاترین سطح بدنه */}
        <CustomCursor />

        {/* محتوای اصلی صفحات */}
        {children}
      </body>
    </html>
  );
}
